CREATE TABLE ENTITY
(
    id INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    attribute VARCHAR(45) NOT NULL
);
CREATE TABLE USER_DETAILS
(
    username VARCHAR(40) PRIMARY KEY NOT NULL,
    password VARCHAR(40) DEFAULT '123456' NOT NULL
);
CREATE UNIQUE INDEX unique_index ON USER_DETAILS (username);
CREATE TABLE USER_AUTH
(
    username VARCHAR(40) NOT NULL,
    authority VARCHAR(40) NOT NULL,
    CONSTRAINT FK_USERNAME FOREIGN KEY (username) REFERENCES USER_DETAILS (username)
);
CREATE INDEX FK_USERNAME ON USER_AUTH (username);
